# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: maven
    - name: Build with Maven
      run: mvn package
      continue-on-error: true

    - name: Notify Zulip on success
      if: steps.buildstep.outcome == 'success'
      run: |
        curl -X POST "https://piccodescript.zulipchat.com/api/v1/external/github?api_key=${{ secrets.ZULIP_API_KEY }}&stream=511550&ignore_private_repositories=true" \
        -H "Content-Type: application/json" \
        -d '{
          "action": "build succeeded",
          "repository": {
            "full_name": "${{ github.repository }}",
            "html_url": "https://github.com/${{ github.repository }}"
          },
          "sender": {
            "login": "${{ github.actor }}",
            "html_url": "https://github.com/${{ github.actor }}"
          }
        }'

    - name: Notify Zulip on failure
      if: steps.buildstep.outcome == 'failure'
      run: |
        curl -X POST "https://piccodescript.zulipchat.com/api/v1/external/github?api_key=${{ secrets.ZULIP_API_KEY }}&stream=511550&ignore_private_repositories=true" \
        -H "Content-Type: application/json" \
        -d '{
          "action": "build failed",
          "repository": {
            "full_name": "${{ github.repository }}",
            "html_url": "https://github.com/${{ github.repository }}"
          },
          "sender": {
            "login": "${{ github.actor }}",
            "html_url": "https://github.com/${{ github.actor }}"
          }
        }'

